import axios from "axios";
import React from "react";
import { useState } from "react";
import { useEffect } from "react";
import { Modal, Table } from "react-bootstrap";
import Loading from "./Loading";

function ViewTestsModal({ show, onHandleShow, id,ResultData,setResultData,setResultTestData }) {
  const [tableData, setTableData] = useState([]);
//   const fetch = () => {
//     axios
//       .post("/api/v1/PatientRegistration/GetTestInfo", {
//         InvestigationId: id,
//       })
//       .then((res) => {
//         setTableData(res?.data?.message);
//       })
//       .catch((err) => console.log(err));
//   };

  useEffect(() => {
    //apiCall
    setTableData([
        {
          Gender: "Male",
          RangeType: "Normal",
          VialID: "HQ047866",
          VisitNo: "9086358",
          PatientName: "Mr Shubh",
          AgeSex: "27 Y 0 M 0 D /Male",
          TestName: "Complete Blood Count (CBC)",
          TestID: "60557653",
          AGE_in_Days: 9862.0,
          OpdIPd: null
        },
        {
          Gender: "Male",
          RangeType: "Normal",
          VialID: "HQ048231",
          VisitNo: "9086406",
          PatientName: "Mr Bhavesh Shah",
          AgeSex: "27 Y 11 M 2 D /Male",
          TestName: "Platelet Count",
          TestID: "60563208",
          AGE_in_Days: 10198.0,
          OpdIPd: null
        },
        {
          Gender: "Female",
          RangeType: "Normal",
          VialID: "HQ048976",
          VisitNo: "9083395",
          PatientName: "Ms Antara Srivastava",
          AgeSex: "32 Y 0 M 0 D /Female",
          TestName: "HbA1C (Glycosylated Haemoglobin)",
          TestID: "60573827",
          AGE_in_Days: 11688.0,
          OpdIPd: null
        },
        {
          Gender: "Female",
          RangeType: "Normal",
          VialID: "HQ048976",
          VisitNo: "9083395",
          PatientName: "Ms Antara Srivastava",
          AgeSex: "32 Y 0 M 0 D /Female",
          TestName: "Complete Blood Count (CBC)",
          TestID: "60573838",
          AGE_in_Days: 11688.0,
          OpdIPd: null
        },
        {
          Gender: "Male",
          RangeType: "Normal",
          VialID: "HQ050012",
          VisitNo: "9097177",
          PatientName: "Mr ZUBER",
          AgeSex: "31 Y 0 M 0 D /Male",
          TestName: "Complete Blood Count (CBC)",
          TestID: "60589309",
          AGE_in_Days: 11323.0,
        OpdIPd: null
        },
        {
            Gender: "Male",
            RangeType: "Normal",
            VialID: "HQ047866",
            VisitNo: "9086358",
            PatientName: "Mr Shubh",
            AgeSex: "27 Y 0 M 0 D /Male",
            TestName: "Complete Blood Count (CBC)",
            TestID: "60557653",
            AGE_in_Days: 9862.0,
            OpdIPd: null
          },
          {
            Gender: "Male",
            RangeType: "Normal",
            VialID: "HQ048231",
            VisitNo: "9086406",
            PatientName: "Mr Bhavesh Shah",
            AgeSex: "27 Y 11 M 2 D /Male",
            TestName: "Platelet Count",
            TestID: "60563208",
            AGE_in_Days: 10198.0,
            OpdIPd: null
          },
          {
            Gender: "Female",
            RangeType: "Normal",
            VialID: "HQ048976",
            VisitNo: "9083395",
            PatientName: "Ms Antara Srivastava",
            AgeSex: "32 Y 0 M 0 D /Female",
            TestName: "HbA1C (Glycosylated Haemoglobin)",
            TestID: "60573827",
            AGE_in_Days: 11688.0,
            OpdIPd: null
          },
          {
            Gender: "Female",
            RangeType: "Normal",
            VialID: "HQ048976",
            VisitNo: "9083395",
            PatientName: "Ms Antara Srivastava",
            AgeSex: "32 Y 0 M 0 D /Female",
            TestName: "Complete Blood Count (CBC)",
            TestID: "60573838",
            AGE_in_Days: 11688.0,
            OpdIPd: null
          },
          {
            Gender: "Male",
            RangeType: "Normal",
            VialID: "HQ050012",
            VisitNo: "9097177",
            PatientName: "Mr ZUBER",
            AgeSex: "31 Y 0 M 0 D /Male",
            TestName: "Complete Blood Count (CBC)",
            TestID: "60589309",
            AGE_in_Days: 11323.0,
          OpdIPd: null
          },
          {
            Gender: "Male",
            RangeType: "Normal",
            VialID: "HQ047866",
            VisitNo: "9086358",
            PatientName: "Mr Shubh",
            AgeSex: "27 Y 0 M 0 D /Male",
            TestName: "Complete Blood Count (CBC)",
            TestID: "60557653",
            AGE_in_Days: 9862.0,
            OpdIPd: null
          },
          {
            Gender: "Male",
            RangeType: "Normal",
            VialID: "HQ048231",
            VisitNo: "9086406",
            PatientName: "Mr Bhavesh Shah",
            AgeSex: "27 Y 11 M 2 D /Male",
            TestName: "Platelet Count",
            TestID: "60563208",
            AGE_in_Days: 10198.0,
            OpdIPd: null
          },
          {
            Gender: "Female",
            RangeType: "Normal",
            VialID: "HQ048976",
            VisitNo: "9083395",
            PatientName: "Ms Antara Srivastava",
            AgeSex: "32 Y 0 M 0 D /Female",
            TestName: "HbA1C (Glycosylated Haemoglobin)",
            TestID: "60573827",
            AGE_in_Days: 11688.0,
            OpdIPd: null
          },
          {
            Gender: "Female",
            RangeType: "Normal",
            VialID: "HQ048976",
            VisitNo: "9083395",
            PatientName: "Ms Antara Srivastava",
            AgeSex: "32 Y 0 M 0 D /Female",
            TestName: "Complete Blood Count (CBC)",
            TestID: "60573838",
            AGE_in_Days: 11688.0,
            OpdIPd: null
          },
          {
            Gender: "Male",
            RangeType: "Normal",
            VialID: "HQ050012",
            VisitNo: "9097177",
            PatientName: "Mr ZUBER",
            AgeSex: "31 Y 0 M 0 D /Male",
            TestName: "Complete Blood Count (CBC)",
            TestID: "60589309",
            AGE_in_Days: 11323.0,
          OpdIPd: null
          },
          {
            Gender: "Male",
            RangeType: "Normal",
            VialID: "HQ047866",
            VisitNo: "9086358",
            PatientName: "Mr Shubh",
            AgeSex: "27 Y 0 M 0 D /Male",
            TestName: "Complete Blood Count (CBC)",
            TestID: "60557653",
            AGE_in_Days: 9862.0,
            OpdIPd: null
          },
          {
            Gender: "Male",
            RangeType: "Normal",
            VialID: "HQ048231",
            VisitNo: "9086406",
            PatientName: "Mr Bhavesh Shah",
            AgeSex: "27 Y 11 M 2 D /Male",
            TestName: "Platelet Count",
            TestID: "60563208",
            AGE_in_Days: 10198.0,
            OpdIPd: null
          },
          {
            Gender: "Female",
            RangeType: "Normal",
            VialID: "HQ048976",
            VisitNo: "9083395",
            PatientName: "Ms Antara Srivastava",
            AgeSex: "32 Y 0 M 0 D /Female",
            TestName: "HbA1C (Glycosylated Haemoglobin)",
            TestID: "60573827",
            AGE_in_Days: 11688.0,
            OpdIPd: null
          },
          {
            Gender: "Female",
            RangeType: "Normal",
            VialID: "HQ048976",
            VisitNo: "9083395",
            PatientName: "Ms Antara Srivastava",
            AgeSex: "32 Y 0 M 0 D /Female",
            TestName: "Complete Blood Count (CBC)",
            TestID: "60573838",
            AGE_in_Days: 11688.0,
            OpdIPd: null
          },
          {
            Gender: "Male",
            RangeType: "Normal",
            VialID: "HQ050012",
            VisitNo: "9097177",
            PatientName: "Mr ZUBER",
            AgeSex: "31 Y 0 M 0 D /Male",
            TestName: "Complete Blood Count (CBC)",
            TestID: "60589309",
            AGE_in_Days: 11323.0,
          OpdIPd: null
          },
          {
            Gender: "Male",
            RangeType: "Normal",
            VialID: "HQ047866",
            VisitNo: "9086358",
            PatientName: "Mr Shubh",
            AgeSex: "27 Y 0 M 0 D /Male",
            TestName: "Complete Blood Count (CBC)",
            TestID: "60557653",
            AGE_in_Days: 9862.0,
            OpdIPd: null
          },
          {
            Gender: "Male",
            RangeType: "Normal",
            VialID: "HQ048231",
            VisitNo: "9086406",
            PatientName: "Mr Bhavesh Shah",
            AgeSex: "27 Y 11 M 2 D /Male",
            TestName: "Platelet Count",
            TestID: "60563208",
            AGE_in_Days: 10198.0,
            OpdIPd: null
          },
          {
            Gender: "Female",
            RangeType: "Normal",
            VialID: "HQ048976",
            VisitNo: "9083395",
            PatientName: "Ms Antara Srivastava",
            AgeSex: "32 Y 0 M 0 D /Female",
            TestName: "HbA1C (Glycosylated Haemoglobin)",
            TestID: "60573827",
            AGE_in_Days: 11688.0,
            OpdIPd: null
          },
          {
            Gender: "Female",
            RangeType: "Normal",
            VialID: "HQ048976",
            VisitNo: "9083395",
            PatientName: "Ms Antara Srivastava",
            AgeSex: "32 Y 0 M 0 D /Female",
            TestName: "Complete Blood Count (CBC)",
            TestID: "60573838",
            AGE_in_Days: 11688.0,
            OpdIPd: null
          },
          {
            Gender: "Male",
            RangeType: "Normal",
            VialID: "HQ050012",
            VisitNo: "9097177",
            PatientName: "Mr ZUBER",
            AgeSex: "31 Y 0 M 0 D /Male",
            TestName: "Complete Blood Count (CBC)",
            TestID: "60589309",
            AGE_in_Days: 11323.0,
          OpdIPd: null
          },
        
      ]
      )
  }, [id]);

  const handleResultData=()=>{
    setResultData([
        {
            "CanSaveAmendment": 1,
            "TestCentreID": 5167,
            "TestIDHash": "747ed034-ff99-4c47-8dbd-d40cea4461cc",
            "Gender": "Male",
            "PackageName": "Alkaline phosphatase (ALP)",
            "TestName": "Alkaline phosphatase (ALP)",
            "TestID": 52039,
            "Value": "",
            "OldValue": "",
            "isMandatory": 0,
            "DataType": "Test",
            "ID": "",
            "DepartmentID": 35,
            "PName": "Mr. VISHNU",
            "SINNo": "BARS/5167/002552",
            "Age": "23 Y 0 M 0 D",
            "PatientCode": "PAT/5167/001615",
            "ReportType": "1",
            "Status": 3,
            "Header": 0,
            "LedgerTransactionNo": "LAB/5167/003553",
            "DisplayReading": null,
            "ReadingFormat": null,
            "MethodName": "",
            "MinValue": "0",
            "IsChecked": 1,
            "AMRMin": 0,
            "AMRMax": 0,
            "MaxValue": "0",
            "COMMENT": null,
            "CommentID": null,
            "InvestigationID": 124,
            "labObservationID": 124,
            "Flag": "",
            "LedgerTransactionID": 7676,
            "isPackage": "0",
            "ItemId": 124,
            "Formula": "",
            "PatientID": 4352,
            "dlcCheck": 0,
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "IsLabOutSource": "False",
            "RegDate": "2024-05-14T13:26:48.000Z",
            "SampleDate": "2024-05-14T13:30:55.000Z",
            "SampleReceiveDate": "2024-06-13T10:53:58.000Z",
            "ResultEnteredDate": "0000-00-00 00:00:00",
            "ApprovedDate": "0000-00-00 00:00:00",
            "LabOutsrcID": 0,
            "Printwithhead": 0,
            "IsHelpMenu": 0,
            "MacReading": null,
            "Reading1": null,
            "Reading2": null,
            "machinename": null,
            "ColorStatus": "#FFFFFF",
            "IsVip": 0,
            "IsMask": 0,
            "isOmit": 0,
            "IsCriticalCheck": 0,
            "isChecked": true,
            "RerunIscheck": false,
            "SaveRangeStatus": 0,
            "currentIndex": 0,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62
        },
        {
            "CanSaveAmendment": 1,
            "TestCentreID": 5167,
            "TestIDHash": "52e24404-e64d-4279-b86a-881641abcdbd",
            "Gender": "Male",
            "PackageName": "LUTEINIZING HORMONE, LH",
            "TestName": "LUTEINIZING HORMONE, LH",
            "TestID": 52040,
            "Value": "",
            "OldValue": "10",
            "isMandatory": 0,
            "DataType": "Test",
            "ID": "",
            "DepartmentID": 35,
            "PName": "Mr. VISHNU",
            "SINNo": "BARS/5167/002552",
            "Age": "23 Y 0 M 0 D",
            "PatientCode": "PAT/5167/001615",
            "ReportType": "1",
            "Status": 3,
            "Header": 0,
            "LedgerTransactionNo": "LAB/5167/003553",
            "DisplayReading": null,
            "ReadingFormat": null,
            "MethodName": "",
            "MinValue": "0",
            "IsChecked": 1,
            "AMRMin": 0,
            "AMRMax": 0,
            "MaxValue": "0",
            "COMMENT": null,
            "CommentID": null,
            "InvestigationID": 1316,
            "labObservationID": 1316,
            "Flag": "",
            "LedgerTransactionID": 7676,
            "isPackage": "0",
            "ItemId": 1316,
            "Formula": "",
            "PatientID": 4352,
            "dlcCheck": 0,
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "IsLabOutSource": "False",
            "RegDate": "2024-05-14T13:26:48.000Z",
            "SampleDate": "2024-05-14T13:30:55.000Z",
            "SampleReceiveDate": "2024-06-13T10:53:58.000Z",
            "ResultEnteredDate": "0000-00-00 00:00:00",
            "ApprovedDate": "0000-00-00 00:00:00",
            "LabOutsrcID": 0,
            "Printwithhead": 0,
            "IsHelpMenu": 0,
            "MacReading": null,
            "Reading1": null,
            "Reading2": null,
            "machinename": null,
            "ColorStatus": "#FFFFFF",
            "IsVip": 0,
            "IsMask": 0,
            "isOmit": 0,
            "IsCriticalCheck": 0,
            "isChecked": true,
            "RerunIscheck": false,
            "SaveRangeStatus": 0,
            "currentIndex": 0,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62
        },
        {
            "CanSaveAmendment": 1,
            "TestCentreID": 5167,
            "TestIDHash": "6a04e55f-3b0b-46b5-a0ec-9125522bff6a",
            "Gender": "Male",
            "PackageName": "Prolactin",
            "TestName": "Prolactin",
            "TestID": 52042,
            "Value": "",
            "OldValue": "10",
            "isMandatory": 0,
            "DataType": "Test",
            "ID": "",
            "DepartmentID": 35,
            "PName": "Mr. VISHNU",
            "SINNo": "BARS/5167/002552",
            "Age": "23 Y 0 M 0 D",
            "PatientCode": "PAT/5167/001615",
            "ReportType": "1",
            "Status": 3,
            "Header": 0,
            "LedgerTransactionNo": "LAB/5167/003553",
            "DisplayReading": "10-100",
            "ReadingFormat": "ul/ml",
            "MethodName": "",
            "MinValue": "10",
            "IsChecked": 1,
            "AMRMin": 2,
            "AMRMax": 150,
            "MaxValue": "100",
            "COMMENT": null,
            "CommentID": null,
            "InvestigationID": 1979,
            "labObservationID": 1979,
            "Flag": "",
            "LedgerTransactionID": 7676,
            "isPackage": "0",
            "ItemId": 1979,
            "Formula": "",
            "PatientID": 4352,
            "dlcCheck": 0,
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "IsLabOutSource": "False",
            "RegDate": "2024-05-14T13:26:48.000Z",
            "SampleDate": "2024-05-14T13:30:55.000Z",
            "SampleReceiveDate": "2024-06-13T10:53:58.000Z",
            "ResultEnteredDate": "0000-00-00 00:00:00",
            "ApprovedDate": "0000-00-00 00:00:00",
            "LabOutsrcID": 0,
            "Printwithhead": 0,
            "IsHelpMenu": 0,
            "MacReading": null,
            "Reading1": null,
            "Reading2": null,
            "machinename": null,
            "ColorStatus": "#FFFFFF",
            "IsVip": 0,
            "IsMask": 0,
            "isOmit": 0,
            "IsCriticalCheck": 0,
            "isChecked": true,
            "RerunIscheck": false,
            "SaveRangeStatus": 0,
            "currentIndex": 0,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62
        },
        {
            "CanSaveAmendment": 1,
            "TestCentreID": 5167,
            "TestIDHash": "b399e75b-51b6-4b0f-9aca-6ed7dad2cf4a",
            "Gender": "Male",
            "PackageName": "KIDNEY FUNCTION TEST (KFT / RFT)",
            "TestName": "Kidney function test profile",
            "TestID": 52043,
            "Value": "HEAD",
            "OldValue": "HEAD",
            "isMandatory": 0,
            "DataType": "Profile",
            "ID": "",
            "DepartmentID": 35,
            "PName": "Mr. VISHNU",
            "SINNo": "BARS/5167/002552",
            "Age": "23 Y 0 M 0 D",
            "PatientCode": "PAT/5167/001615",
            "ReportType": "1",
            "Status": 3,
            "Header": 1,
            "LedgerTransactionNo": "LAB/5167/003553",
            "DisplayReading": null,
            "ReadingFormat": null,
            "MethodName": "",
            "MinValue": "0",
            "IsChecked": 1,
            "AMRMin": 0,
            "AMRMax": 0,
            "MaxValue": "0",
            "COMMENT": null,
            "CommentID": null,
            "InvestigationID": 1285,
            "labObservationID": 3244,
            "Flag": "",
            "LedgerTransactionID": 7676,
            "isPackage": "1",
            "ItemId": 1285,
            "Formula": "",
            "PatientID": 4352,
            "dlcCheck": 0,
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "IsLabOutSource": "False",
            "RegDate": "2024-05-14T13:26:48.000Z",
            "SampleDate": "2024-05-14T13:30:55.000Z",
            "SampleReceiveDate": "2024-06-13T10:53:58.000Z",
            "ResultEnteredDate": "0000-00-00 00:00:00",
            "ApprovedDate": "0000-00-00 00:00:00",
            "LabOutsrcID": 0,
            "Printwithhead": 0,
            "IsHelpMenu": 0,
            "MacReading": null,
            "Reading1": null,
            "Reading2": null,
            "machinename": null,
            "ColorStatus": "#FFFFFF",
            "IsVip": 0,
            "IsMask": 0,
            "isOmit": 0,
            "IsCriticalCheck": 0,
            "isChecked": true,
            "RerunIscheck": false,
            "SaveRangeStatus": 0,
            "currentIndex": 0,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62
        },
        {
            "CanSaveAmendment": 1,
            "TestCentreID": 5167,
            "TestIDHash": "b399e75b-51b6-4b0f-9aca-6ed7dad2cf4a",
            "Gender": "Male",
            "PackageName": "KIDNEY FUNCTION TEST (KFT / RFT)",
            "TestName": "Urea",
            "TestID": 52043,
            "Value": "",
            "OldValue": "10",
            "isMandatory": 0,
            "DataType": "Profile",
            "ID": "",
            "DepartmentID": 35,
            "PName": "Mr. VISHNU",
            "SINNo": "BARS/5167/002552",
            "Age": "23 Y 0 M 0 D",
            "PatientCode": "PAT/5167/001615",
            "ReportType": "1",
            "Status": 3,
            "Header": 0,
            "LedgerTransactionNo": "LAB/5167/003553",
            "DisplayReading": null,
            "ReadingFormat": null,
            "MethodName": "",
            "MinValue": "0",
            "IsChecked": 1,
            "AMRMin": 0,
            "AMRMax": 0,
            "MaxValue": "0",
            "COMMENT": null,
            "CommentID": null,
            "InvestigationID": 1285,
            "labObservationID": 2953,
            "Flag": "",
            "LedgerTransactionID": 7676,
            "isPackage": "1",
            "ItemId": 1285,
            "Formula": "",
            "PatientID": 4352,
            "dlcCheck": 0,
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "IsLabOutSource": "False",
            "RegDate": "2024-05-14T13:26:48.000Z",
            "SampleDate": "2024-05-14T13:30:55.000Z",
            "SampleReceiveDate": "2024-06-13T10:53:58.000Z",
            "ResultEnteredDate": "0000-00-00 00:00:00",
            "ApprovedDate": "0000-00-00 00:00:00",
            "LabOutsrcID": 0,
            "Printwithhead": 0,
            "IsHelpMenu": 0,
            "MacReading": null,
            "Reading1": null,
            "Reading2": null,
            "machinename": null,
            "ColorStatus": "#FFFFFF",
            "IsVip": 0,
            "IsMask": 0,
            "isOmit": 0,
            "IsCriticalCheck": 0,
            "isChecked": true,
            "RerunIscheck": false,
            "SaveRangeStatus": 0,
            "currentIndex": 0,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62
        },
        {
            "CanSaveAmendment": 1,
            "TestCentreID": 5167,
            "TestIDHash": "b399e75b-51b6-4b0f-9aca-6ed7dad2cf4a",
            "Gender": "Male",
            "PackageName": "KIDNEY FUNCTION TEST (KFT / RFT)",
            "TestName": "Creatinine",
            "TestID": 52043,
            "Value": "",
            "OldValue": "10",
            "isMandatory": 0,
            "DataType": "Profile",
            "ID": "",
            "DepartmentID": 35,
            "PName": "Mr. VISHNU",
            "SINNo": "BARS/5167/002552",
            "Age": "23 Y 0 M 0 D",
            "PatientCode": "PAT/5167/001615",
            "ReportType": "1",
            "Status": 3,
            "Header": 0,
            "LedgerTransactionNo": "LAB/5167/003553",
            "DisplayReading": null,
            "ReadingFormat": null,
            "MethodName": "",
            "MinValue": "0",
            "IsChecked": 1,
            "AMRMin": 0,
            "AMRMax": 0,
            "MaxValue": "0",
            "COMMENT": null,
            "CommentID": null,
            "InvestigationID": 1285,
            "labObservationID": 582,
            "Flag": "",
            "LedgerTransactionID": 7676,
            "isPackage": "1",
            "ItemId": 1285,
            "Formula": "",
            "PatientID": 4352,
            "dlcCheck": 0,
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "IsLabOutSource": "False",
            "RegDate": "2024-05-14T13:26:48.000Z",
            "SampleDate": "2024-05-14T13:30:55.000Z",
            "SampleReceiveDate": "2024-06-13T10:53:58.000Z",
            "ResultEnteredDate": "0000-00-00 00:00:00",
            "ApprovedDate": "0000-00-00 00:00:00",
            "LabOutsrcID": 0,
            "Printwithhead": 0,
            "IsHelpMenu": 0,
            "MacReading": null,
            "Reading1": null,
            "Reading2": null,
            "machinename": null,
            "ColorStatus": "#FFFFFF",
            "IsVip": 0,
            "IsMask": 0,
            "isOmit": 0,
            "IsCriticalCheck": 0,
            "isChecked": true,
            "RerunIscheck": false,
            "SaveRangeStatus": 0,
            "currentIndex": 0,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62
        },
        {
            "CanSaveAmendment": 1,
            "TestCentreID": 5167,
            "TestIDHash": "b399e75b-51b6-4b0f-9aca-6ed7dad2cf4a",
            "Gender": "Male",
            "PackageName": "KIDNEY FUNCTION TEST (KFT / RFT)",
            "TestName": "Uric acid",
            "TestID": 52043,
            "Value": "",
            "OldValue": "10",
            "isMandatory": 0,
            "DataType": "Profile",
            "ID": "",
            "DepartmentID": 35,
            "PName": "Mr. VISHNU",
            "SINNo": "BARS/5167/002552",
            "Age": "23 Y 0 M 0 D",
            "PatientCode": "PAT/5167/001615",
            "ReportType": "1",
            "Status": 3,
            "Header": 0,
            "LedgerTransactionNo": "LAB/5167/003553",
            "DisplayReading": null,
            "ReadingFormat": null,
            "MethodName": "",
            "MinValue": "0",
            "IsChecked": 1,
            "AMRMin": 0,
            "AMRMax": 0,
            "MaxValue": "0",
            "COMMENT": null,
            "CommentID": null,
            "InvestigationID": 1285,
            "labObservationID": 2966,
            "Flag": "",
            "LedgerTransactionID": 7676,
            "isPackage": "1",
            "ItemId": 1285,
            "Formula": "",
            "PatientID": 4352,
            "dlcCheck": 0,
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "IsLabOutSource": "False",
            "RegDate": "2024-05-14T13:26:48.000Z",
            "SampleDate": "2024-05-14T13:30:55.000Z",
            "SampleReceiveDate": "2024-06-13T10:53:58.000Z",
            "ResultEnteredDate": "0000-00-00 00:00:00",
            "ApprovedDate": "0000-00-00 00:00:00",
            "LabOutsrcID": 0,
            "Printwithhead": 0,
            "IsHelpMenu": 0,
            "MacReading": null,
            "Reading1": null,
            "Reading2": null,
            "machinename": null,
            "ColorStatus": "#FFFFFF",
            "IsVip": 0,
            "IsMask": 0,
            "isOmit": 0,
            "IsCriticalCheck": 0,
            "isChecked": true,
            "RerunIscheck": false,
            "SaveRangeStatus": 0,
            "currentIndex": 0,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62
        },
        {
            "CanSaveAmendment": 1,
            "TestCentreID": 5167,
            "TestIDHash": "b399e75b-51b6-4b0f-9aca-6ed7dad2cf4a",
            "Gender": "Male",
            "PackageName": "KIDNEY FUNCTION TEST (KFT / RFT)",
            "TestName": "Sodium (Na)",
            "TestID": 52043,
            "Value": "",
            "OldValue": "10",
            "isMandatory": 0,
            "DataType": "Profile",
            "ID": "",
            "DepartmentID": 35,
            "PName": "Mr. VISHNU",
            "SINNo": "BARS/5167/002552",
            "Age": "23 Y 0 M 0 D",
            "PatientCode": "PAT/5167/001615",
            "ReportType": "1",
            "Status": 3,
            "Header": 0,
            "LedgerTransactionNo": "LAB/5167/003553",
            "DisplayReading": null,
            "ReadingFormat": null,
            "MethodName": "",
            "MinValue": "0",
            "IsChecked": 1,
            "AMRMin": 0,
            "AMRMax": 0,
            "MaxValue": "0",
            "COMMENT": null,
            "CommentID": null,
            "InvestigationID": 1285,
            "labObservationID": 2093,
            "Flag": "",
            "LedgerTransactionID": 7676,
            "isPackage": "1",
            "ItemId": 1285,
            "Formula": "",
            "PatientID": 4352,
            "dlcCheck": 0,
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "IsLabOutSource": "False",
            "RegDate": "2024-05-14T13:26:48.000Z",
            "SampleDate": "2024-05-14T13:30:55.000Z",
            "SampleReceiveDate": "2024-06-13T10:53:58.000Z",
            "ResultEnteredDate": "0000-00-00 00:00:00",
            "ApprovedDate": "0000-00-00 00:00:00",
            "LabOutsrcID": 0,
            "Printwithhead": 0,
            "IsHelpMenu": 0,
            "MacReading": null,
            "Reading1": null,
            "Reading2": null,
            "machinename": null,
            "ColorStatus": "#FFFFFF",
            "IsVip": 0,
            "IsMask": 0,
            "isOmit": 0,
            "IsCriticalCheck": 0,
            "isChecked": true,
            "RerunIscheck": false,
            "SaveRangeStatus": 0,
            "currentIndex": 0,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62
        },
        {
            "CanSaveAmendment": 1,
            "TestCentreID": 5167,
            "TestIDHash": "b399e75b-51b6-4b0f-9aca-6ed7dad2cf4a",
            "Gender": "Male",
            "PackageName": "KIDNEY FUNCTION TEST (KFT / RFT)",
            "TestName": "Potassium (K)",
            "TestID": 52043,
            "Value": "",
            "OldValue": "0.2",
            "isMandatory": 0,
            "DataType": "Profile",
            "ID": "",
            "DepartmentID": 35,
            "PName": "Mr. VISHNU",
            "SINNo": "BARS/5167/002552",
            "Age": "23 Y 0 M 0 D",
            "PatientCode": "PAT/5167/001615",
            "ReportType": "1",
            "Status": 3,
            "Header": 0,
            "LedgerTransactionNo": "LAB/5167/003553",
            "DisplayReading": null,
            "ReadingFormat": null,
            "MethodName": "",
            "MinValue": "0",
            "IsChecked": 1,
            "AMRMin": 0,
            "AMRMax": 0,
            "MaxValue": "0",
            "COMMENT": null,
            "CommentID": null,
            "InvestigationID": 1285,
            "labObservationID": 1972,
            "Flag": "",
            "LedgerTransactionID": 7676,
            "isPackage": "1",
            "ItemId": 1285,
            "Formula": "(2953&+582&)/100",
            "PatientID": 4352,
            "dlcCheck": 0,
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "IsLabOutSource": "False",
            "RegDate": "2024-05-14T13:26:48.000Z",
            "SampleDate": "2024-05-14T13:30:55.000Z",
            "SampleReceiveDate": "2024-06-13T10:53:58.000Z",
            "ResultEnteredDate": "0000-00-00 00:00:00",
            "ApprovedDate": "0000-00-00 00:00:00",
            "LabOutsrcID": 0,
            "Printwithhead": 0,
            "IsHelpMenu": 0,
            "MacReading": null,
            "Reading1": null,
            "Reading2": null,
            "machinename": null,
            "ColorStatus": "#FFFFFF",
            "IsVip": 0,
            "IsMask": 0,
            "isOmit": 0,
            "IsCriticalCheck": 0,
            "isChecked": true,
            "RerunIscheck": false,
            "SaveRangeStatus": 0,
            "currentIndex": 0,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62
        },
        {
            "CanSaveAmendment": 1,
            "TestCentreID": 5167,
            "TestIDHash": "b399e75b-51b6-4b0f-9aca-6ed7dad2cf4a",
            "Gender": "Male",
            "PackageName": "KIDNEY FUNCTION TEST (KFT / RFT)",
            "TestName": "Chloride (Cl)",
            "TestID": 52043,
            "Value": "",
            "OldValue": "10",
            "isMandatory": 0,
            "DataType": "Profile",
            "ID": "",
            "DepartmentID": 35,
            "PName": "Mr. VISHNU",
            "SINNo": "BARS/5167/002552",
            "Age": "23 Y 0 M 0 D",
            "PatientCode": "PAT/5167/001615",
            "ReportType": "1",
            "Status": 3,
            "Header": 0,
            "LedgerTransactionNo": "LAB/5167/003553",
            "DisplayReading": null,
            "ReadingFormat": null,
            "MethodName": "",
            "MinValue": "0",
            "IsChecked": 1,
            "AMRMin": 0,
            "AMRMax": 0,
            "MaxValue": "0",
            "COMMENT": null,
            "CommentID": null,
            "InvestigationID": 1285,
            "labObservationID": 476,
            "Flag": "",
            "LedgerTransactionID": 7676,
            "isPackage": "1",
            "ItemId": 1285,
            "Formula": "",
            "PatientID": 4352,
            "dlcCheck": 0,
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "IsLabOutSource": "False",
            "RegDate": "2024-05-14T13:26:48.000Z",
            "SampleDate": "2024-05-14T13:30:55.000Z",
            "SampleReceiveDate": "2024-06-13T10:53:58.000Z",
            "ResultEnteredDate": "0000-00-00 00:00:00",
            "ApprovedDate": "0000-00-00 00:00:00",
            "LabOutsrcID": 0,
            "Printwithhead": 0,
            "IsHelpMenu": 0,
            "MacReading": null,
            "Reading1": null,
            "Reading2": null,
            "machinename": null,
            "ColorStatus": "#FFFFFF",
            "IsVip": 0,
            "IsMask": 0,
            "isOmit": 0,
            "IsCriticalCheck": 0,
            "isChecked": true,
            "RerunIscheck": false,
            "SaveRangeStatus": 0,
            "currentIndex": 0,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62
        },
        {
            "CanSaveAmendment": 1,
            "TestCentreID": 5167,
            "TestIDHash": "b399e75b-51b6-4b0f-9aca-6ed7dad2cf4a",
            "Gender": "Male",
            "PackageName": "KIDNEY FUNCTION TEST (KFT / RFT)",
            "TestName": "Calcium total",
            "TestID": 52043,
            "Value": "",
            "OldValue": "10",
            "isMandatory": 0,
            "DataType": "Profile",
            "ID": "",
            "DepartmentID": 35,
            "PName": "Mr. VISHNU",
            "SINNo": "BARS/5167/002552",
            "Age": "23 Y 0 M 0 D",
            "PatientCode": "PAT/5167/001615",
            "ReportType": "1",
            "Status": 3,
            "Header": 0,
            "LedgerTransactionNo": "LAB/5167/003553",
            "DisplayReading": null,
            "ReadingFormat": null,
            "MethodName": "",
            "MinValue": "0",
            "IsChecked": 1,
            "AMRMin": 0,
            "AMRMax": 0,
            "MaxValue": "0",
            "COMMENT": null,
            "CommentID": null,
            "InvestigationID": 1285,
            "labObservationID": 347,
            "Flag": "",
            "LedgerTransactionID": 7676,
            "isPackage": "1",
            "ItemId": 1285,
            "Formula": "",
            "PatientID": 4352,
            "dlcCheck": 0,
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "IsLabOutSource": "False",
            "RegDate": "2024-05-14T13:26:48.000Z",
            "SampleDate": "2024-05-14T13:30:55.000Z",
            "SampleReceiveDate": "2024-06-13T10:53:58.000Z",
            "ResultEnteredDate": "0000-00-00 00:00:00",
            "ApprovedDate": "0000-00-00 00:00:00",
            "LabOutsrcID": 0,
            "Printwithhead": 0,
            "IsHelpMenu": 0,
            "MacReading": null,
            "Reading1": null,
            "Reading2": null,
            "machinename": null,
            "ColorStatus": "#FFFFFF",
            "IsVip": 0,
            "IsMask": 0,
            "isOmit": 0,
            "IsCriticalCheck": 0,
            "isChecked": true,
            "RerunIscheck": false,
            "SaveRangeStatus": 0,
            "currentIndex": 0,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62
        }
    ])
    setResultTestData([
        {
            "PatientCode": "PAT/5167/001615",
            "datatype": "Test",
            "ApprovedBy": "0",
            "TestIDHash": "747ed034-ff99-4c47-8dbd-d40cea4461cc",
            "SINNO": "BARS/5167/002552",
            "InvestigationID": 124,
            "PackageName": "Alkaline phosphatase (ALP)",
            "Status": 3,
            "TestID": 52039,
            "LedgerTransactionID": 7676,
            "LedgerTransactionNo": "LAB/5167/003553",
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "PatientName": "Mr. VISHNU",
            "DATE": "14-May-24 06:56PM",
            "HLMOPDIPDNo": "",
            "COMMENT": null,
            "IsDLCCheck": 0,
            "Printwithhead": 0,
            "Remarks": "",
            "SampleRemarks": "Serum",
            "IsChecked": 1,
            "OldValueDate": null,
            "isChecked": true,
            "outSource": 1,
            "isDocumentUpload": 0,
            "TestCenterId": 5167,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62,
            "labObservationID": 124
        },
        {
            "PatientCode": "PAT/5167/001615",
            "datatype": "Test",
            "ApprovedBy": "0",
            "TestIDHash": "52e24404-e64d-4279-b86a-881641abcdbd",
            "SINNO": "BARS/5167/002552",
            "InvestigationID": 1316,
            "PackageName": "LUTEINIZING HORMONE, LH",
            "Status": 3,
            "TestID": 52040,
            "LedgerTransactionID": 7676,
            "LedgerTransactionNo": "LAB/5167/003553",
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "PatientName": "Mr. VISHNU",
            "DATE": "14-May-24 06:56PM",
            "HLMOPDIPDNo": "",
            "COMMENT": null,
            "IsDLCCheck": 0,
            "Printwithhead": 0,
            "Remarks": "",
            "SampleRemarks": "Serum",
            "IsChecked": 1,
            "OldValueDate": "14-May-24 11:58 AM",
            "isChecked": true,
            "outSource": 1,
            "isDocumentUpload": 0,
            "TestCenterId": 5167,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62,
            "labObservationID": 1316
        },
        {
            "PatientCode": "PAT/5167/001615",
            "datatype": "Test",
            "ApprovedBy": "0",
            "TestIDHash": "6a04e55f-3b0b-46b5-a0ec-9125522bff6a",
            "SINNO": "BARS/5167/002552",
            "InvestigationID": 1979,
            "PackageName": "Prolactin",
            "Status": 3,
            "TestID": 52042,
            "LedgerTransactionID": 7676,
            "LedgerTransactionNo": "LAB/5167/003553",
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "PatientName": "Mr. VISHNU",
            "DATE": "14-May-24 06:56PM",
            "HLMOPDIPDNo": "",
            "COMMENT": null,
            "IsDLCCheck": 0,
            "Printwithhead": 0,
            "Remarks": "",
            "SampleRemarks": "Overnight fasting preferred.",
            "IsChecked": 1,
            "OldValueDate": "14-May-24 11:58 AM",
            "isChecked": true,
            "outSource": 1,
            "isDocumentUpload": 0,
            "TestCenterId": 5167,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62,
            "labObservationID": 1979
        },
        {
            "PatientCode": "PAT/5167/001615",
            "datatype": "Profile",
            "ApprovedBy": "0",
            "TestIDHash": "b399e75b-51b6-4b0f-9aca-6ed7dad2cf4a",
            "SINNO": "BARS/5167/002552",
            "InvestigationID": 1285,
            "PackageName": "KIDNEY FUNCTION TEST (KFT / RFT)",
            "Status": 3,
            "TestID": 52043,
            "LedgerTransactionID": 7676,
            "LedgerTransactionNo": "LAB/5167/003553",
            "Centre": "HARISHs",
            "RateType": "Itodse1",
            "ReferDoctor": "Dr. Self",
            "PatientName": "Mr. VISHNU",
            "DATE": "14-May-24 06:56PM",
            "HLMOPDIPDNo": "",
            "COMMENT": null,
            "IsDLCCheck": 0,
            "Printwithhead": 0,
            "Remarks": "",
            "SampleRemarks": "Serum",
            "IsChecked": 1,
            "OldValueDate": "14-May-24 11:58 AM",
            "isChecked": true,
            "outSource": 1,
            "isDocumentUpload": 0,
            "TestCenterId": 5167,
            "Mobile": "9599534346",
            "PEmail": "",
            "MachineId": 62,
            "labObservationID": 1285
        }
    ])
   onHandleShow()

  }

  return (
    <Modal show={show} onHide={onHandleShow} id="ModalViewtest"  >
      <Modal.Header className="modal-header">
        <Modal.Title className="modal-title">
          Test Information
        </Modal.Title>
        <button type="button" className="close" onClick={onHandleShow}>
          ×
        </button>
      </Modal.Header>
      <Modal.Body>
        {tableData?.length > 0 ? (
          <Table responsive bordered hover striped>
            <thead>
              <tr>
                <th>Vial ID</th>
                <th>Visit No</th>
                <th>Patient Name</th>
                <th>Age/Sex</th>
                <th>TestName</th>
              </tr>
            </thead>
            <tbody>
              {tableData?.map((data, index) => (
                <tr key={index}>
                    
                    <td>
  <div style={{cursor:'pointer'}} onClick={handleResultData}>
    <span className="fa fa-eyedropper" title="Show Result Entry" ></span>
    {data?.VialID}
  </div>
</td>

                  <td>{data?.VisitNo}</td>
                  <td>{data?.PatientName}</td>
                  <td>{data?.AgeSex}</td>
                  <td>{data?.TestName}</td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          <Loading />
        )}
      </Modal.Body>
    </Modal>
  );
}

export default ViewTestsModal;
